name: Deploy to Production

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
        
    - name: Install server dependencies
      run: |
        cd server
        npm ci
        
    - name: Install client dependencies  
      run: |
        cd client
        npm ci
        
    - name: Build client
      run: |
        cd client
        npm run build
      env:
        VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        
    - name: Deploy to Render/Railway (example)
      run: |
        # Your deployment commands here
        echo "Deploying with secrets..."
      env:
        SWID: ${{ secrets.SWID }}
        ESPN_S2: ${{ secrets.ESPN_S2 }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # if using Render
        
    # Alternative: Deploy to Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./client
